services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=studDB'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=myuser'
    ports:
      - '3303:3306'


  app:
    image: deliverysystem:1.0.0
    ports:
      - '8085:8080'
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/deliveryDB
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: myuser
      spring.datasource.password: password
    depends_on:
      - mysql
    networks:
      - default
    restart: always